### ISSUE TITLE
Correlations enrichment

### ISSUE THREAD

**Issue by cgchute** [NCATS-Tangerine/fhir_publish#2]
as we discussed, it would make sense that for the major detail variables (labs, diagnoses, procedures, and HPO codes), it  would be useful to make a top-10 or so correlations for:
a) each variable to itself
b) each variable to the other three

this is a substantial enrichment of correlation data that will be easy (if tedious) to reflect in the model, but not easy (but still tedious) to implement.

**Comment by hsolbrig** [comment]
Correlation matrix completely updated
